### ISSUE TITLE
BattleBit Remastered

### ISSUE THREAD

**Issue by TibixDev** [AreWeAntiCheatYet/AreWeAntiCheatYet#354] opened 2022-02-21 18:23 UTC
### Game Title

BattleBit Remastered

### Game Website

https://store.steampowered.com/app/671860/BattleBit_Remastered/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://imgur.com/a/yAH2j8S

**Comment by Fijxu** [comment] 2023-04-27 00:54
They will remove EAC and likely break Linux support in some weeks (one or 3 more weeks).

![image](https://user-images.githubusercontent.com/61166695/234732428-9ffbb307-999f-4a13-bfa9-cfacb2a8ac37.png)

Thanks SgtOkiDoki, +250 hours directly into the trash.

**Comment by Curve** [comment] 2023-04-27 09:39
> They will remove EAC and likely break Linux support in some weeks (one or 3 more weeks).
> 
> ![image](https://user-images.githubusercontent.com/61166695/234732428-9ffbb307-999f-4a13-bfa9-cfacb2a8ac37.png)
> 
> Thanks SgtOkiDoki, +250 hours directly into the trash.

Oh man too bad.
I could go on a rant about people believing they can actually stop cheating by employing some shady commercial anti-cheat solution but I'll keep that for another day.

**Comment by Fijxu** [comment] 2023-04-28 06:50
![image](https://user-images.githubusercontent.com/61166695/235074985-8854010e-e2ee-46f1-984c-e4cbf09fcc34.png)

Confirmed that Linux support will be removed by this awful anti cheat...
Very sad, at least for me. Mas this game is so fucking good.

**Comment by Curve** [comment] 2023-04-28 07:14
> ![image](https://user-images.githubusercontent.com/61166695/235074985-8854010e-e2ee-46f1-984c-e4cbf09fcc34.png)
> 
> Confirmed that Linux support will be removed by this awful anti cheat...
> Very sad, at least for me. Mas this game is so fucking good.

Any idea what the new anticheat is? So that we can update it here accordingly as well as the status

**Comment by Fijxu** [comment] 2023-04-28 23:19
> Any idea what the new anticheat is? So that we can update it here accordingly as well as the status

Private info for now according to the developers, probably a not a well known AC so crackers can't bypass it easily

**Comment by Starz0r** [comment] 2023-05-15 04:16
Marking this as `Running` in preparation for the [May 20th playtest](https://steamcommunity.com/games/1611740/announcements/detail/3730713625515970791). Looks like they've changed their official anti-cheat to FACEIT, but also allow Easy Anti-Cheat for community servers (you can still get FACEIT on "rented" community servers). Might also mark this as `Broken` after the play test if the situation does not get better, or if the developers do not communicate the problem.

**Closed** 2023-05-15 04:20 UTC
Labels: enhancement
