### ISSUE TITLE
Wrong image for EA SPORTS™ WRC

### ISSUE THREAD

**Issue by vikingnope** [AreWeAntiCheatYet/AreWeAntiCheatYet#1725] opened 2024-09-13 15:50 UTC
Currently the image is as follows:

![image](https://github.com/user-attachments/assets/9ea322de-1611-42b8-9938-1f8626dabee4)

Should be:

![image](https://github.com/user-attachments/assets/4d1579ec-9b04-45bd-84a5-87620407bbf2)

**Comment by Starz0r** [comment] 2024-10-07 22:58
Apologies! This isn't entirely our fault, we pull images like this from SteamGridDB, and sometimes this happens. Since we try to get the closest to the game name as possible, but if no images exist for it, then it occasionally pulls the next closest match to the game's name.

I'm planning to allow for overrides on this, because there are quite a few cases where this happens, but if you want to do something about this in the intermediate, you can file an entry on SteamGridDB, and it'll be pulled the next time the site is generated.

**Comment by vikingnope** [comment] 2024-10-08 05:46
There seems to be one already: https://www.steamgriddb.com/grid/363571

**Comment by Starz0r** [comment] 2024-10-10 01:57
So I think the issue is that this happens to be a collection, and I don't think those can be used as the cover. And even if it could, the name is wrong, since it'll try matching by "EA Sports" first, and it isn't prefixed with that, it won't actually be used. Anyone that resubmits it with the correct game title, then it will actually be found and picked up on the site.

**Comment by vikingnope** [comment] 2024-10-11 05:44
Managed to get them updated, should be fixed now: https://www.steamgriddb.com/game/5426979

**Comment by Starz0r** [comment] 2024-10-13 22:18
> Managed to get them to update it, should be fixed now: [steamgriddb.com/game/5426979](https://www.steamgriddb.com/game/5426979)

That's pretty incredible that you managed to do that!

Looks like it got picked up now that the site got regenerated, so this should be fixed for now.

**Closed by Starz0r** 2024-10-13 22:18 UTC
Labels: bug
